### ISSUE TITLE
Menu Icon

### ISSUE THREAD

**Issue by brunomachadors** [brunomachadors/payment-company-case#5]

**Comment by AlineGorga** [comment]
**Task: Implementação do menu icon**

**Descrição**
O menu icon é um ícone que será utilizado para abrir e fechar o menu lateral da home da aplicação Klarna. A implementação deve seguir as seguintes regras de negócio:
* O ícone deve ser exibido no canto superior esquerdo da tela, ao lado do logo da aplicação
* O menu lateral deve conter 4 abas: Home, Meus cartões, Solicitar Cartão e Sobre Nós (os nomes ainda serão validados)


**Critérios de aceitação:**
* Ao clicar no ícone, o menu lateral deve ser aberto. Deve haver uma oção de fechar a direita.
* Ao clica na opçã de fechar, o menu lateral deve ser fechado. O ícone deve ser alterado novamente para o ícone de menu.
* O ícone deve ser responsivo e se adaptar a diferentes tamanhos de tela.
