### ISSUE TITLE
Implementação da customização de cartão -  Plano Classic

### ISSUE THREAD

**Issue by brunomachadors** [brunomachadors/payment-company-case#6]

**Comment by AlineGorga** [comment]
**Task: Implementação da customização de cartão para o Plano Classic**

**Descrição**
A customização de cartão é uma funcionalidade que permite aos clientes personalizarem o design do seu cartão de crédito.

**Critérios de Aceitação**
* O plano Classic permitea escolha pelo usuário entre dois modelos de design pré definidos (black e pink)
* O cliente poderá visualizar uma prévia do design do cartão
* O cliente terá um botão embaixo escrito "selecionar design"

**Comment by AlineGorga** [comment]
![Image](https://github.com/brunomachadors/payment-company-case/assets/134301395/02a8ecec-0c8b-46dc-afa6-87c76b0a01ee)

**Comment by AlineGorga** [comment]
Referência:

https://www.klarna.com/uk/card/
